### ISSUE TITLE
[FireFox] Getting out of memory error 

### ISSUE THREAD

**Issue by darkworks** [austinksmith/Hamsters.js#41] opened 2017-09-14 04:43 UTC
* ***What version of the library are you using?***

latest version of library 

* ***What operating system are you seeing the issue on?***

windows 7 

* ***Which platform (and or) browser are you seeing the issue on?***

Core JS (Vanilla)

* ***What is the version of the platform (and or) browser you are seeing the issue on?***

Am on Firefox browser , using core js with html5 canvas doing some heavy image processing so i mostly use hamster.js to split the image portion for processing between threads , recently i have started getting error  out of memory and object could not be cloned  , so i was wondering how overcome this memory issue , also any idea to allocate more memory in browser to JS so that out of memory issue not occur as i have 16GB RAM
```
Error Hamster #0: Line 0 in : uncaught exception: out of memory  hamsters.js:607:5
	onerror /js/vendor/hamsters/hamsters.js:607:5
uncaught exception: out of memory
```

```
Error Hamster #0: Line 0 in : DataCloneError: The object could not be cloned.  hamsters.js:607:5
	onerror /js/vendor/hamsters/hamsters.js:607:5
DataCloneError: The object could not be cloned.
```

**Comment by darkworks** [comment] 2017-09-20 05:31
ok thanks i fixed it by turning off persistence mode

**Comment by austinksmith** [comment] 2017-09-20 13:29
@darkworks I am reopening this issue as it concerns me a little that persistence mode has the memory issue but non persistence mode does not. If you could send me a demo link so I can investigate and fix persistence mode I would really appreciate that. Email it to me if you are uncomfortable with it being posted here, thanks!

**Comment by darkworks** [comment] 2017-09-20 18:33
ok on weekend when free i will prepare demo link for you to check .

**Comment by austinksmith** [comment] 2017-09-25 15:50
Any updates @darkworks  ?

**Comment by darkworks** [comment] 2017-09-26 04:38
sorry for delay i have mailed you check  if any question let me know 

thanks

**Comment by austinksmith** [comment] 2017-09-26 16:06
Awesome thanks, I have a question about why you are invoking 32 threads
instead of simply letting the library decide a thread count? When you run
32 threads that's quite a bit of overhead and is likely slowing down the
application. I have not had time to dig into it deeper yet but my first
recommendation is to let the library invoke the threads based on logical
cores available. On my machine it would ideally use 8 threads total as that
is what I have available, over utilizing threads can have a negative impact
on performance.

**Comment by darkworks** [comment] 2017-09-27 01:03
max_threads , ya good point i will set it to logical processor number , however it not matter that much because threads creation i control with loops , i mean i create threads manually based on logical cores  , count and wait for their completion , because i cant leave threads creation auto to library because i have to split work among threads and then i have to wait for all threads to complete to merge their results  and then process it. ... if you check console log of browser you will see its creating not more than 8 threads and it will create more once the other finished their job.

**Comment by austinksmith** [comment] 2017-09-27 13:50
@darkworks  I think you need to read what the library does for you since that should all be handled automatically by the library. When you initiate the library and have say 8 processors available the library will make use of a **maximum** of 8 threads at any time, you can still start functions that use more than 8 threads and the library will intelligently manage all that for you without having to do it manually. In other words when making use of persistence mode there should never be any situation that more than 8 threads are alive at any given time, having a function that invokes 32 threads won't cause any issues even if you only have 1 core available for execution since the library will simply pool the remaining work and keep the threads you have active until ALL the work is complete. 

I will dig deeper into this later today but you might need to rethink the way you are using the library as there is no need for you to manually aggregate thread results back together since the library can do that for you as well.

**Comment by darkworks** [comment] 2017-09-27 15:45
hmmm i do not understand how it can split work among threads , 
for example 

i have 600 dpi image i dump  pixel data like 
for example
 
```
var imgData = canvas_active().getImageData(0, 0, WIDTH, HEIGHT);
   var params = {
		imgData: FILE.imgData,
		red: red,
		green: green,
		blue: blue,
		};
    hamsters.run(params, function() {
		var imgData = params.imgData;
		var red =  params.red;
		var green =  params.green;
		var blue =  params.blue;
	
			for (var y = 0; y < imgData.height; ++y) {
				for (var x = 0; x < imgData.width; ++x) {
					var index = (y * imgData.width + x) * 4; // index of the current pixel
					
					if(imgData.data[index+3] != 0){
						imgData.data[index] = red;
						imgData.data[index+1] = green;
						imgData.data[index+2] = blue;
					}
				} // for X end
			} // for Y end
			rtn.data.push(imgData);
	    }, function(ctdata) {
		imgData = ctdata;
		}, hamsters.maxThreads, true);
);
```

so can you tell how library can split imgData  among threads and also the two inside for loops how to set to get their respective range of imgData ? 

thanks

**Comment by austinksmith** [comment] 2017-09-29 12:37
@darkworks Do you have a link to the actual repository this is stored on? It's proving difficult to figure out exactly what calls are being made where at the moment.

**Comment by darkworks** [comment] 2017-09-30 19:17
sorry we do not have repo , i work in it directly

**Comment by darkworks** [comment] 2017-09-30 19:31
i have mailed you some info check it 

thanks

**Comment by austinksmith** [comment] 2017-09-30 20:06
@darkworks  Give this release a try using persistence mode and report back to me, thanks!

https://github.com/austinksmith/Hamsters.js/releases/tag/v4.2.1

**Comment by austinksmith** [comment] 2017-10-01 18:15
Take a look at the new release I put out v4.2.1 it now forces the garbage
collector to run sooner when a thread has finished completing its task.
This should make a large difference in heap usage over time.

This message (including any attachments) may contain confidential,
proprietary, privileged and/or private information. The information is
intended to be for the use of the individual or entity designated above. If
you are not the intended recipient of this message, please notify the
sender immediately, and delete the message and any attachments. Any
disclosure, reproduction, distribution or other use of this message or any
attachments by an individual or entity other than the intended recipient is
prohibited.

**Comment by austinksmith** [comment] 2017-10-04 20:04
@darkworks I am closing this ticket as you emailed and said v4.2.1 has resolved the out of memory issues.

**Closed by austinksmith** 2017-10-04 20:04 UTC
Labels: help wanted

**Comment by darkworks** [comment] 2017-10-05 04:45
ya v4.2.1 have fixed memory issue in persistence mode , now its working ok :) 

thanks
